language: ruby
rvm:
  - rbx-2.6
install:
  - gem install rubinius-actor -V
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec 
branches:
  only:
    - master
os:
- linux
- osx
addons:
    code_climate:
        repo_token: 6537e4c035e1b3a7294eee716197b11662f2ff53ec46ef7496e0c74f895fbee7
