language: ruby
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $RVM
  - echo $LANG
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y llvm-3.4 llvm-3.4-dev ; fi
  - if [ $TRAVIS_OS_NAME ==   osx ]; then brew update ; fi
  - if [ $TRAVIS_OS_NAME ==   osx ]; then brew install llvm35 ; fi
  - if [ $TRAVIS_OS_NAME ==   osx ]; then brew link --force llvm35 ; fi
  - rvm use $RVM --install --fuzzy
install:
  - gem install rubinius-actor -V
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec 
branches:
  only:
    - master
env:
  matrix:
  - RVM=rbx-2.2.10 LANG="en_US.UTF-8"
os:
- linux
- osx
addons:
    code_climate:
        repo_token: 6537e4c035e1b3a7294eee716197b11662f2ff53ec46ef7496e0c74f895fbee7
