sudo: false
language: ruby
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $RVM
  - echo $LANG
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi
  - rvm use $RVM --install --fuzzy
  - gem update --system
  - gem --version
install:
  - gem install rubinius-actor -V
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - ../mspec/bin/mspec 
branches:
  only:
    - master
env:
  matrix:
  - RVM=rbx-2.2.10 LANG="en_US.UTF-8"
os:
- linux
- osx

