language: ruby
rvm:
- rbx-3.13
install:
- gem install codeclimate-test-reporter
- gem install rubinius-actor
- git clone https://github.com/ruby/mspec.git ../mspec
script:
- "../mspec/bin/mspec"
branches:
  only:
  - master
os:
- linux
- osx
addons:
  code_climate:
    repo_token: 6537e4c035e1b3a7294eee716197b11662f2ff53ec46ef7496e0c74f895fbee7
deploy:
  provider: rubygems
  api_key:
    secure: wRVHQHUQKc21TTRnVbAfriPMCqJH05Rkhi1LXF6IdZVS4etwiEN7uBjP41dwyZT4yAPYpRKtorbSrDZ9BLhApYuebp10ds0OcstY4/UKNnMJioO5FIyZWIFRBAWiuVdADKCJnL/gr97jwSR67Va7JJ9Ec6LOFH0+u6Wbj1pZIvWFcjJx2ZvDRnUZJ5bwCrb89iik7thyfDXlLweD84wTx7eCk5/cWnAuylZBWkb+wX32MwLycXkp4VLxRGdFbk+W3mXWYs9W0q8zMFbrK8oETrwgr11+1sye3eoi4cW1jtI+q6Zri4JnhYjYK4dUgaABYLo5UFDtPMbpmvnmfOGPmvLJx9efuJGbAr4hoDy2d7cL8jsiZgQ9WSBFNOiDZZD3iDbKWlNRB9ALO0T3rWTf5VotnpU34rrBS/wDlJMzv3ErO+jJkkGEeUPiz6nAdGdLsl6XbsBSFr3+FGR4FI7J7UKNmwizXAccBdPM5GtlZTdEq2PyGQsWxTyiOJ/HKEnDRhNQE3ZsP5IU7u1Gth+ye4rMAigdyiJcNIqv8FLYkBj08+oinq9mOla4fUboXtNQZQvOovS6D0yzFd2brkBWtHPwIK4GPpYjVUN06HnJHhTD8kM4NVkW/bdRKFjejzKIitX99LoK3LK7wTUNaIonl9/Y11z53pfbBhjq/qYkR7c=
  gemspec: fresh-mc.gemspec
